name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    step:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/DrHJekyll/top-api-nest/top-api-nest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
